### PR TITLE
feat: add C# support via tree-sitter

### PR DESCRIPTION
**Pull request by gnerkus**

### CODE REVIEW

**Comment by jayu** [comment]
Thank you for the PR, I'm AFK right now but I will review and test it asap.

I'm impressed that you crack on all internals and made it work!

**Comment by SnowPowerCore** [comment]
Hello do you have any updates on this, C# is great to be present

**Comment by jayu** [comment]
Hi, I forgot about it 🤦I Will review and test the pr this week and merge it if everything will be fine

**Comment by jayu** [comment]
Hi @gnerkus @SnowPowerCore I've checked the PR, run the extension and it works, but I consider C# support at this stage as experimental. 
Use cases covered in tests works, but far away from feature parity with other parsers. 
I will merge it and release it, but still keep the original issue open as further improvements have to be done. 

Anyway, thanks a lot for your input !

**Comment by SnowPowerCore** [comment]
This is amazing, thank you

**Pull request merged**
